##
## Kap PROJECT, 2023
## C Lib - Tests
## File description:
## Makefile for tests lib
##

PATH_TESTS = ./tests/

SRC_TESTS	=	$(PATH_TESTS)kap_string_tests.c			\
				$(PATH_TESTS)kap_string_errors_tests.c	\
				$(PATH_TESTS)kap_text_tests.c			\
				$(PATH_TESTS)kap_string_calcul_tests.c	\
				#$(PATH_TESTS)kap_memory_tests.c		\

OBJ_TESTS	=	$(SRC_TESTS:.c=.o)
