##
## KAP PROJECT, 2023
## C Lib - Memory
## File description:
## Makefile for memory lib
##

PATH_MEMORY = ./src/memory/

SRC_MEMORY	=	$(PATH_MEMORY)kap_free.c	\
				$(PATH_MEMORY)kap_alloc.c	\

OBJ_MEMORY	=	$(SRC_MEMORY:.c=.o)
