##
## KAP PROJECT, 2023
## C Lib
## File description:
## Makefile
##

KPRINTF_PATH = ./src/kprint/

SRC_KPRINTF	=	$(KPRINTF_PATH)kprintf_init.c		\
				$(KPRINTF_PATH)kprintf_call.c		\
				$(KPRINTF_PATH)kprintf_put_char.c	\
				$(KPRINTF_PATH)kprint_put_others.c	\


KPRINTF_OBJ	=	$(SRC_KPRINTF:.c=.o)
