##
## KAP PROJECT, 2023
## C Lib - String
## File description:
## Makefile for string lib
##

PATH_STRING = ./src/string/

SRC_STRING	=	$(PATH_STRING)string_add.c				\
				$(PATH_STRING)string_check.c			\
				$(PATH_STRING)string_contains.c			\
				$(PATH_STRING)string_copy.c				\
				$(PATH_STRING)string_index_of.c			\
				$(PATH_STRING)string_init.c				\
				$(PATH_STRING)string_is_number.c		\
				$(PATH_STRING)string_last_index_of.c	\
				$(PATH_STRING)string_length.c			\
				$(PATH_STRING)string_remove.c			\
				$(PATH_STRING)string_start_with.c		\
				$(PATH_STRING)string_end_with.c			\

OBJ_STRING	=	$(SRC_STRING:.c=.o)
