##
## KAP PROJECT, 2023
## C Lib - All Lib
## File description:
## Makefile for all lib
##

PATH_ALL = ./src/

include $(PATH_ALL)memory/Makefile
include $(PATH_ALL)string/Makefile
include $(PATH_ALL)list/Makefile
include $(PATH_ALL)kprint/Makefile
#include $(PATH_ALL)kapparsor/Makefile
include $(PATH_ALL)math/Makefile

SRC = $(SRC_MEMORY) $(SRC_STRING) $(SRC_LIST) $(SRC_KPRINTF) $(SRC_MATH)
#SRC += $(SRC_PARSER)

OBJ = $(SRC:.c=.o)
