##
## KAP PROJECT, 2023
## C Lib
## File description:
## Makefile
##

PATH_CHAINED_LIST	= ./src/list/chained/

SRC_CHAINED_LIST	=	$(PATH_CHAINED_LIST)chained_push.c		\
						$(PATH_CHAINED_LIST)init_chained_list.c	\

OBJ_CHAINED_LIST	=	$(SRC_CHAINED_LIST:.c=.o)

SRC_LIST	=	$(SRC_CHAINED_LIST)

OBJ_LIST	=	$(OBJ_CHAINED_LIST)
