name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

    - name: configure
      run: |
        sudo apt-get install libcriterion-dev
        pip install gcovr

    - name: make
      run: make build_tests

    - name: run unit tests
      run: make start_runnig_tests
    
    - name: run gcovrage
      run: make check_coverage
